
name: 'dbt_example'
version: '1.0.0'

profile: 'dbt_example'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# exemple de variables

vars:
  ambiente: 'desenvolvimento'
  data_minima: '2023-01-01'
  schema_nome: 'desenvolvimento_schema'


models:
  dbt_example:
    staging:
      schema: staging
      materialized: table
      tags: ['staging']
    
    intermediate:
      materialized: ephemeral
      tags: ['intermediate']

    marts:
      schema: marts
      materialized: table
      tags: ['marts']

seeds:
  dbt_example:
    schema: seeds
    tags: ['seeds']
    
snapshots:
  dbt_example:
    tags: ['snapshots']
    schema: snapshots